### ISSUE TITLE
Generate vaccination records for pets without pending vaccination records

### ISSUE THREAD

**Issue by josdem** [josdem/py-vetlog-analyzer#27]
As **a user**, I want to generate vaccination records for all pets without vaccination records in pending status **so that** I can scan and automatically generate desired records

**Acceptance Criteria**
- I can see vaccination records generated for all pets without vaccination records on pending status
- All tests are passsing

**Notes**
- In this task we include only dog pets to make it easier.

**References**
- https://github.com/josdem/vetlog-spring-boot/wiki/ER-Driagram
- https://github.com/josdem/vetlog-spring-boot/wiki/Vaccination-Program

**Comment by sahasra21321** [comment]
Hi, Can i take-up this task.

**Comment by josdem** [comment]
> Hi, Can i take-up this task.

Hi @sahasra21321 ; Absolutely, your collaboration is appreciated. let me know if you have any questions.

**Comment by josdem** [comment]
Hi @sahasra21321 Please find here a dump from my local database, in it you will find a couple of pets:
- Spooky has a couple of vaccination records in Pending status
- Sora has no records and the script should create all required records based on its birthdate.
- 
[vetlog20241006.txt](https://github.com/user-attachments/files/17270761/vetlog20241006.txt)

**Comment by josdem** [comment]
PR merged: https://github.com/josdem/py-vetlog-analyzer/pull/39
