### ISSUE TITLE
Fix Maintainability issues reported by SonarCloud

### ISSUE THREAD

**Issue by josdem** [josdem/py-vetlog-analyzer#30]
As **developer**, I would like to solve as much as possible maintainability issues reported by SonarCloud **so that** I can improve reliability in the code.

**Acceptance Criteria**
- I can see 80% of maintainability issues solved
- All test are passing.

**References**
https://sonarcloud.io/project/issues?impactSoftwareQualities=MAINTAINABILITY&issueStatuses=OPEN%2CCONFIRMED&id=josdem_py-vetlog-analyzer

**Comment by sahasra21321** [comment]
Hi, Can i take-up this task.

**Comment by josdem** [comment]
> Hi, Can i take-up this task.

Hi @sahasra21321 ; Absolutely, your collaboration is appreciated, let me know if you have any questions.

**Comment by josdem** [comment]
PR merged: https://github.com/josdem/py-vetlog-analyzer/pull/38
